name: Deploy Cloudflare Pages

on:
  push:
    branches:
      - main # Deploy when changes are pushed to the main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    name: Deploy Pages and Worker
    runs-on: ubuntu-latest

    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set Up Node.js
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Step 5: Install Wrangler CLI v4
      - name: Install Wrangler
        run: pnpm add -g wrangler@4

      # Step 6: Create Cloudflare Pages project if it doesn't exist
      - name: Create Cloudflare Pages Project
        run: ./scripts/create-cloudflare-project.sh
        continue-on-error: true

      # Step 7: Build Project for Pages
      - name: Build Project
        run: pnpm run build:pages

      # Step 8: Verify build output directory exists
      - name: Verify Build Output
        run: test -d build/client && echo "✅ Build output found"

      # Step 9: Deploy to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        run: wrangler pages deploy build/client --project-name boltecho
        continue-on-error: true

      # Step 10: Verify deployment
      - name: Verify Deployment
        run: |
          echo "Checking deployment status..."
          sleep 10  # Wait a bit for deployment to process
          wrangler pages deployment list --project-name boltecho --json | head -20
